### ISSUE TITLE
canvas recording does not work in safari

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#3789] opened 2023-01-30 06:44 UTC
[https://app.highlight.run/1074/sessions/H3VODGLerDlbIwWc6QqsZadXCWKr](https://app.highlight.run/1074/sessions/H3VODGLerDlbIwWc6QqsZadXCWKr)

**Comment by soulwawa** [comment] 2023-07-23 15:02
Hi.
Is this problem still there?
It's the same site, but the contents of Chrome and Safari are different

**Comment by Vadman97** [comment] 2024-01-29 16:58
duplicate of #6775

**Closed by Vadman97** 2024-01-29 16:58 UTC
