### ISSUE TITLE
Add backend SDK option for environment

### ISSUE THREAD

**Issue by et** [highlight/highlight#6177] opened 2023-08-01 14:42 UTC
Currently, the only way to set `environment` is through the [client SDK](https://www.highlight.io/docs/sdk/client#environment). Similar to the problem with `version`, this data is embedded entirely on the session object. For backend only apps, a session will not exist.

We should:

* investigate what the OTEL semantic meaning of `environment` is
* allow it to be set on backend SDKs
* set it on error_object and make is visible in the UI
* allow `environment` to be searched in logs

**Comment by ccschmitz** [comment] 2023-10-31 18:20
@jay-khatri @Vadman97 is this something you'd like to prioritize in Q4? Going to take it out of the Q3 milestone. Please reassign if you want to get this done in the near future!

**Comment by Vadman97** [comment] 2023-10-31 18:26
Thanks @ccschmitz - just heard this again from some more customers (who i've linked to the new ticket), so i'll mark this a dup of that one. Duplicate of #7004

**Closed by Vadman97** 2023-10-31 18:26 UTC
Labels: future-work
