### ISSUE TITLE
improve chrome-extension filtering logic 

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5609] opened 2023-06-09 17:37 UTC
we should filter out the entire error object rather than filtering the stacktrace for the error.

* setting should filter out chrome extension errors on the ingest, just like we do [with manual filters](https://github.com/highlight/highlight/blob/dc2d0ecbc731587ce2cbf47a5cc947cb7cfe7afd/backend/public-graph/graph/resolver.go#L2434-L2441) 
* we should switch the chrome extension filter setting to default-off

**Comment by et** [comment] 2023-06-09 17:38
Dupe of #5604

**Closed by et** 2023-06-09 17:38 UTC
Labels: bug
