### ISSUE TITLE
Next.js app directory SSR error documentation is incorrect

### ISSUE THREAD

**Issue by twalker1998** [highlight/highlight#7117] opened 2023-11-08 23:02 UTC
**Describe the bug**
Can't send errors from Next.js server-rendered components to Highlight.io

**To Reproduce**

1. In a Next.js app-directory enabled application, follow documentation here https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js/app-router#catch-serverside-render-ssr-errors
2. Validate configuration by following steps here https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js/app-router#validate-ssr-error-capture

**Expected behavior**
Error sent to app.highlight.io

**Actual behavior**
Client side error caused by imports from `@highlight-run/next/ssr`
<img width="1800" alt="Screenshot 2023-11-08 at 16 09 45" src="https://github.com/highlight/highlight/assets/22465068/c528b44c-97ee-4767-b5be-cb6b81a85971">

**Comment by jay-khatri** [comment] 2023-11-08 23:02
Hi, this is Highlight.io's [GitSorted](https://gitsorted.onrender.com/) bot. 
                While one of our developers cooks up a reply, please search for anything related in our [Discord](https://highlight.io/community) or on our [docs](https://highlight.io/docs). 
                Also, if you haven't posted a reproduction, please do so (we prioritize those tickets).

**Comment by jay-khatri** [comment] 2023-11-25 15:43
@deltaepsilon @Vadman97 perhaps we can take a look this upcoming week?

**Comment by Vadman97** [comment] 2023-11-27 18:01
@twalker1998 - looks like a duplicate of the dynamic import of react error - tracking in #7118

**Closed by Vadman97** 2023-11-27 18:01 UTC
Labels: external bug / request

**Comment by Vadman97** [comment] 2023-11-27 19:05
Should be fixed with [7.2.3](https://www.npmjs.com/package/@highlight-run/next/v/7.2.3)
